name: CI

on:
  workflow_dispatch:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/prepare

      - name: Set up npm auth
        run: |
          npm config set //registry.npmjs.org/:_authToken "${NPM_TOKEN}"
          npm config set registry "https://registry.npmjs.org/"
          npm config set always-auth true
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: bun run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
