name: CI

on:
  workflow_dispatch:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - name: Setup Node + npm auth
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # must be an Automation token
      - run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish
        run: bun run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
