name: CI

on:
  workflow_dispatch:
  workflow_call:

jobs:
  release:
    environment: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - name: Set up npm auth
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

      - run: bun run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
